{-# LANGUAGE NoImplicitPrelude #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE OverloadedStrings #-}
module Data.FHIR.Resources.PatientSpec where

import qualified Data.Aeson                   as J
import qualified Data.ByteString.Builder as BB
import qualified Data.ByteString.Lazy as BL
import qualified Data.ByteString.Lazy.UTF8    as BLU
import           Data.FHIR.Datatypes.Internal
import           Data.FHIR.Datatypes.XML
import           Data.FHIR.Datatypes.XhtmlDiv
import           Data.FHIR.Resources.DomainResource
import           Data.FHIR.Resources
import qualified Xmlbf.Xeno                   as X
import qualified Xmlbf                        as Xmlbf
import           RIO
import qualified RIO.HashMap                  as HM
import Data.Text.Encoding                     as TE
import Test.Hspec

--decode :: Text -> Resource
decode t = Xmlbf.runParser Xmlbf.fromXml $ fromRight [] $ X.fromRawXml (TE.encodeUtf8 t)

bsEncode :: [Xmlbf.Node] -> ByteString
bsEncode = BL.toStrict . BB.toLazyByteString . Xmlbf.encode


spec :: Spec
spec = do
  describe "Patient" $ do
    it "decode patient type" $ do
      J.decode (BLU.fromString "{\"resourceType\":\"Patient\",\"id\":\"0001fd81-1d53-46f4-b673-0301496ba959\"}")
        `shouldBe` Just Patient {
          patientId = Just "0001fd81-1d53-46f4-b673-0301496ba959"
        , patientMeta = Nothing
        , patientImplicitRules = Nothing
        , patientLanguage = Nothing
        , patientText = Nothing
        , patientExtension = []
        , patientModifierExtension = []
        , patientIdentifier = []
        , patientActive= Nothing
        , patientName = []
        , patientTelecom = []
        , patientGender = Nothing
        , patientBirthDate = Nothing
        , patientMultipleBirth = Nothing
        , patientAddress = []
        , patientMaritalStatus = Nothing
        , patientDeceased = Nothing
        , patientPhoto = []
        , patientContact = []
        , patientCommunication = []
        , patientGeneralPractitioner = []
        , patientManagingOrganization = Nothing
        , patientLink = []
        }

    it "decode patient text" $ do
      J.decode (BLU.fromString "{\"resourceType\":\"Patient\",\"text\":{\"status\":\"generated\",\"div\":\"<div xmlns=\\\"http://www.w3.org/1999/xhtml\\\">Generated by <a href=\\\"https://github.com/synthetichealth/synthea\\\">Synthea</a>.Version identifier: v2.4.0-272-gbd747730\\n.   Person seed: 292861142008678757  Population seed: 1563971124564</div>\"}}")
        `shouldBe` Just Patient {
          patientId = Nothing
        , patientMeta = Nothing
        , patientImplicitRules = Nothing
        , patientLanguage = Nothing
        , patientText = Just (Narrative {narrativeAttribs = [], narrativeId = Nothing, narrativeExtension = [], narrativeStatus = NsGenerated, narrativeXhtmlDiv = XhtmlDiv (Div [] [FText "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by <a href=\"https://github.com/synthetichealth/synthea\">Synthea</a>.Version identifier: v2.4.0-272-gbd747730\n.   Person seed: 292861142008678757  Population seed: 1563971124564</div>"])})
        , patientExtension = []
        , patientModifierExtension = []
        , patientIdentifier = []
        , patientActive= Nothing
        , patientName = []
        , patientTelecom = []
        , patientGender = Nothing
        , patientBirthDate = Nothing
        , patientMultipleBirth = Nothing
        , patientAddress = []
        , patientMaritalStatus = Nothing
        , patientDeceased = Nothing
        , patientPhoto = []
        , patientContact = []
        , patientCommunication = []
        , patientGeneralPractitioner = []
        , patientManagingOrganization = Nothing
        , patientLink = []
        }
    it "decode patient extension" $ do
      J.decode (BLU.fromString "{\"resourceType\":\"Patient\",\"extension\":[{\"url\":\"http://hl7.org/fhir/us/core/StructureDefinition/us-core-race\",\"extension\":[{\"url\":\"ombCategory\",\"valueCoding\":{\"system\":\"urn:oid:2.16.840.1.113883.6.238\",\"code\":\"2054-5\",\"display\":\"Black or African American\"}},{\"url\":\"text\",\"valueString\":\"Black or African American\"}]},{\"url\":\"http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity\",\"extension\":[{\"url\":\"ombCategory\",\"valueCoding\":{\"system\":\"urn:oid:2.16.840.1.113883.6.238\",\"code\":\"2186-5\",\"display\":\"Not Hispanic or Latino\"}},{\"url\":\"text\",\"valueString\":\"Not Hispanic or Latino\"}]},{\"url\":\"http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName\",\"valueString\":\"Ariadna374 Zapata667\"},{\"url\":\"http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex\",\"valueCode\":\"F\"},{\"url\":\"http://hl7.org/fhir/StructureDefinition/patient-birthPlace\",\"valueAddress\":{\"city\":\"Wesley\",\"state\":\"Saint Andrew Parish\",\"country\":\"DM\"}},{\"url\":\"http://synthetichealth.github.io/synthea/disability-adjusted-life-years\",\"valueDecimal\":0.0},{\"url\":\"http://synthetichealth.github.io/synthea/quality-adjusted-life-years\",\"valueDecimal\":2.0}]}")
        `shouldBe` Just Patient {
          patientId = Nothing
        , patientMeta = Nothing
        , patientImplicitRules = Nothing
        , patientLanguage = Nothing
        , patientText = Nothing
        , patientExtension = [Extension {extensionUrl = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race", extensionId = Nothing, extensionExtension = [Extension {extensionUrl = "ombCategory", extensionId = Nothing, extensionExtension = [], extensionValue = Just (ExtensionValueCoding (Coding {codingAttribs = [], codingId = Nothing, codingExtension = [], codingSystem = Just "urn:oid:2.16.840.1.113883.6.238", codingVersion = Nothing, codingCode = Just "2054-5", codingDisplay = Just "Black or African American", codingUserSelected = Nothing}))},Extension {extensionUrl = "text", extensionId = Nothing, extensionExtension = [], extensionValue = Just (ExtensionValueString "Black or African American")}], extensionValue = Nothing},Extension {extensionUrl = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity", extensionId = Nothing, extensionExtension = [Extension {extensionUrl = "ombCategory", extensionId = Nothing, extensionExtension = [], extensionValue = Just (ExtensionValueCoding (Coding {codingAttribs = [], codingId = Nothing, codingExtension = [], codingSystem = Just "urn:oid:2.16.840.1.113883.6.238", codingVersion = Nothing, codingCode = Just "2186-5", codingDisplay = Just "Not Hispanic or Latino", codingUserSelected = Nothing}))},Extension {extensionUrl = "text", extensionId = Nothing, extensionExtension = [], extensionValue = Just (ExtensionValueString "Not Hispanic or Latino")}], extensionValue = Nothing},Extension {extensionUrl = "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName", extensionId = Nothing, extensionExtension = [], extensionValue = Just (ExtensionValueString "Ariadna374 Zapata667")},Extension {extensionUrl = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex", extensionId = Nothing, extensionExtension = [], extensionValue = Just (ExtensionValueCode "F")},Extension {extensionUrl = "http://hl7.org/fhir/StructureDefinition/patient-birthPlace", extensionId = Nothing, extensionExtension = [], extensionValue = Just (ExtensionValueAddress (Address {addressId = Nothing, addressExtension = [], addressUse = Nothing, addressType = Nothing, addressText = Nothing, addressLine = [], addressCity = Just "Wesley", addressDistrict = Nothing, addressState = Just "Saint Andrew Parish", addressPostalCode = Nothing, addressCountry = Just "DM", addressPeriod = Nothing}))},Extension {extensionUrl = "http://synthetichealth.github.io/synthea/disability-adjusted-life-years", extensionId = Nothing, extensionExtension = [], extensionValue = Just (ExtensionValueDecimal 0.0)},Extension {extensionUrl = "http://synthetichealth.github.io/synthea/quality-adjusted-life-years", extensionId = Nothing, extensionExtension = [], extensionValue = Just (ExtensionValueDecimal 2.0)}]
        , patientModifierExtension = []
        , patientIdentifier = []
        , patientActive= Nothing
        , patientName = []
        , patientTelecom = []
        , patientGender = Nothing
        , patientBirthDate = Nothing
        , patientMultipleBirth = Nothing
        , patientAddress = []
        , patientMaritalStatus = Nothing
        , patientDeceased = Nothing
        , patientPhoto = []
        , patientContact = []
        , patientCommunication = []
        , patientGeneralPractitioner = []
        , patientManagingOrganization = Nothing
        , patientLink = []
        }
    it "decode patient identifier" $ do
      J.decode (BLU.fromString "{\"resourceType\":\"Patient\",\"identifier\":[{\"system\":\"https://github.com/synthetichealth/synthea\",\"value\":\"9547e8f0-42d5-48b2-96d2-dcc7e2d2c70e\"},{\"type\":{\"coding\":[{\"system\":\"http://terminology.hl7.org/CodeSystem/v2-0203\",\"code\":\"MR\",\"display\":\"Medical Record Number\"}],\"text\":\"Medical Record Number\"},\"system\":\"http://hospital.smarthealthit.org\",\"value\":\"9547e8f0-42d5-48b2-96d2-dcc7e2d2c70e\"},{\"type\":{\"coding\":[{\"system\":\"http://terminology.hl7.org/CodeSystem/v2-0203\",\"code\":\"SS\",\"display\":\"Social Security Number\"}],\"text\":\"Social Security Number\"},\"system\":\"http://hl7.org/fhir/sid/us-ssn\",\"value\":\"999-11-1542\"}]}")
        `shouldBe` Just Patient {
          patientId = Nothing
        , patientMeta = Nothing
        , patientImplicitRules = Nothing
        , patientLanguage = Nothing
        , patientText = Nothing
        , patientExtension = []
        , patientModifierExtension = []
        , patientIdentifier = [Identifier {identifierAttribs = [], identifierId = Nothing, identifierExtension = [], identifierUse = Nothing, identifierType = Nothing, identifierSystem = Just "https://github.com/synthetichealth/synthea", identifierValue = Just "9547e8f0-42d5-48b2-96d2-dcc7e2d2c70e", identifierPeriod = Nothing, identifierAssigner = Nothing},Identifier {identifierAttribs = [], identifierId = Nothing, identifierExtension = [], identifierUse = Nothing, identifierType = Just (CodeableConcept {codeableConceptAttribs = [], codeableConceptId = Nothing, codeableConceptExtension = [], codeableConceptCoding = [Coding {codingAttribs = [], codingId = Nothing, codingExtension = [], codingSystem = Just "http://terminology.hl7.org/CodeSystem/v2-0203", codingVersion = Nothing, codingCode = Just "MR", codingDisplay = Just "Medical Record Number", codingUserSelected = Nothing}], codeableConceptText = Just "Medical Record Number"}), identifierSystem = Just "http://hospital.smarthealthit.org", identifierValue = Just "9547e8f0-42d5-48b2-96d2-dcc7e2d2c70e", identifierPeriod = Nothing, identifierAssigner = Nothing},Identifier {identifierAttribs = [], identifierId = Nothing, identifierExtension = [], identifierUse = Nothing, identifierType = Just (CodeableConcept {codeableConceptAttribs = [], codeableConceptId = Nothing, codeableConceptExtension = [], codeableConceptCoding = [Coding {codingAttribs = [], codingId = Nothing, codingExtension = [], codingSystem = Just "http://terminology.hl7.org/CodeSystem/v2-0203", codingVersion = Nothing, codingCode = Just "SS", codingDisplay = Just "Social Security Number", codingUserSelected = Nothing}], codeableConceptText = Just "Social Security Number"}), identifierSystem = Just "http://hl7.org/fhir/sid/us-ssn", identifierValue = Just "999-11-1542", identifierPeriod = Nothing, identifierAssigner = Nothing}]
        , patientActive= Nothing
        , patientName = []
        , patientTelecom = []
        , patientGender = Nothing
        , patientBirthDate = Nothing
        , patientMultipleBirth = Nothing
        , patientAddress = []
        , patientMaritalStatus = Nothing
        , patientDeceased = Nothing
        , patientPhoto = []
        , patientContact = []
        , patientCommunication = []
        , patientGeneralPractitioner = []
        , patientManagingOrganization = Nothing
        , patientLink = []
        }
    it "decode patient rest" $ do
      J.decode (BLU.fromString "{\"resourceType\":\"Patient\",\"name\":[{\"use\":\"official\",\"family\":\"Dueñas839\",\"given\":[\"Leonor133\"]}],\"telecom\":[{\"system\":\"phone\",\"value\":\"555-890-8795\",\"use\":\"home\"}],\"gender\":\"female\",\"birthDate\":\"2016-12-16\",\"address\":[{\"extension\":[{\"url\":\"http://hl7.org/fhir/StructureDefinition/geolocation\",\"extension\":[{\"url\":\"latitude\",\"valueDecimal\":42.342933521629355},{\"url\":\"longitude\",\"valueDecimal\":-70.93353385375897}]}],\"line\":[\"126 Raynor Vale\"],\"city\":\"Boston\",\"state\":\"Massachusetts\",\"postalCode\":\"02108\",\"country\":\"US\"}],\"maritalStatus\":{\"coding\":[{\"system\":\"http://terminology.hl7.org/CodeSystem/v3-MaritalStatus\",\"code\":\"S\",\"display\":\"Never Married\"}],\"text\":\"Never Married\"},\"multipleBirthBoolean\":false,\"communication\":[{\"language\":{\"coding\":[{\"system\":\"urn:ietf:bcp:47\",\"code\":\"es\",\"display\":\"Spanish\"}],\"text\":\"Spanish\"}}]}")
        `shouldBe` Just Patient {
          patientId = Nothing
        , patientMeta = Nothing
        , patientImplicitRules = Nothing
        , patientLanguage = Nothing
        , patientText = Nothing
        , patientExtension = []
        , patientModifierExtension = []
        , patientIdentifier = []
        , patientActive = Nothing
        , patientName = [HumanName {humanNameAttribs = [], humanNameId = Nothing, humanNameExtension = [], humanNameUse = Just NuOfficial, humanNameText = Nothing, humanNameFamily = Just "Due\241as839", humanNameGiven = ["Leonor133"], humanNamePrefix = [], humanNameSuffix = [], humanNamePeriod = Nothing}]
        , patientTelecom = [ContactPoint {contactPointAttribs = [], contactPointId = Nothing, contactPointExtension = [], contactPointSystem = Just CpsPhone, contactPointValue = Just "555-890-8795", contactPointUse = Just CpuHome, contactPointRank = Nothing, contactPointPeriod = Nothing}]
        , patientGender = Just AgFemale
        , patientBirthDate = Just "2016-12-16"
        , patientDeceased = Nothing
        , patientAddress = [Address {addressId = Nothing, addressExtension = [Extension {extensionUrl = "http://hl7.org/fhir/StructureDefinition/geolocation", extensionId = Nothing, extensionExtension = [Extension {extensionUrl = "latitude", extensionId = Nothing, extensionExtension = [], extensionValue = Just (ExtensionValueDecimal 42.342933521629355)},Extension {extensionUrl = "longitude", extensionId = Nothing, extensionExtension = [], extensionValue = Just (ExtensionValueDecimal (-70.93353385375897))}], extensionValue = Nothing}], addressUse = Nothing, addressType = Nothing, addressText = Nothing, addressLine = ["126 Raynor Vale"], addressCity = Just "Boston", addressDistrict = Nothing, addressState = Just "Massachusetts", addressPostalCode = Just "02108", addressCountry = Just "US", addressPeriod = Nothing}]
        , patientMaritalStatus = Just (CodeableConcept {codeableConceptAttribs = [], codeableConceptId = Nothing, codeableConceptExtension = [], codeableConceptCoding = [Coding {codingAttribs = [], codingId = Nothing, codingExtension = [], codingSystem = Just "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus", codingVersion = Nothing, codingCode = Just "S", codingDisplay = Just "Never Married", codingUserSelected = Nothing}], codeableConceptText = Just "Never Married"})
        , patientMultipleBirth = Just (PatientMultipleBirthBoolean False)
        , patientPhoto = []
        , patientContact = []
        , patientCommunication = [PatientCommunication {
              patientCommunicationAttrId = Nothing
            , patientCommunicationExtension = []
            , patientCommunicationModifierExtension = []
            , patientCommunicationLanguage = CodeableConcept {codeableConceptAttribs = [], codeableConceptId = Nothing, codeableConceptExtension = [], codeableConceptCoding = [Coding {codingAttribs = [], codingId = Nothing, codingExtension = [], codingSystem = Just "urn:ietf:bcp:47", codingVersion = Nothing, codingCode = Just "es", codingDisplay = Just "Spanish", codingUserSelected = Nothing}], codeableConceptText = Just "Spanish"}, patientCommunicationPreferred = Nothing}]
        , patientGeneralPractitioner = []
        , patientManagingOrganization = Nothing
        , patientLink = []
        }
    it "decode patient" $ do
      J.decode (BLU.fromString "{\"resourceType\":\"Patient\",\"id\":\"0001fd81-1d53-46f4-b673-0301496ba959\",\"text\":{\"status\":\"generated\",\"div\":\"<div xmlns=\\\"http://www.w3.org/1999/xhtml\\\">Generated by <a href=\\\"https://github.com/synthetichealth/synthea\\\">Synthea</a>.Version identifier: v2.4.0-272-gbd747730\n .   Person seed: 292861142008678757  Population seed: 1563971124564</div>\"},\"extension\":[{\"url\":\"http://hl7.org/fhir/us/core/StructureDefinition/us-core-race\",\"extension\":[{\"url\":\"ombCategory\",\"valueCoding\":{\"system\":\"urn:oid:2.16.840.1.113883.6.238\",\"code\":\"2054-5\",\"display\":\"Black or African American\"}},{\"url\":\"text\",\"valueString\":\"Black or African American\"}]},{\"url\":\"http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity\",\"extension\":[{\"url\":\"ombCategory\",\"valueCoding\":{\"system\":\"urn:oid:2.16.840.1.113883.6.238\",\"code\":\"2186-5\",\"display\":\"Not Hispanic or Latino\"}},{\"url\":\"text\",\"valueString\":\"Not Hispanic or Latino\"}]},{\"url\":\"http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName\",\"valueString\":\"Ariadna374 Zapata667\"},{\"url\":\"http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex\",\"valueCode\":\"F\"},{\"url\":\"http://hl7.org/fhir/StructureDefinition/patient-birthPlace\",\"valueAddress\":{\"city\":\"Wesley\",\"state\":\"Saint Andrew Parish\",\"country\":\"DM\"}},{\"url\":\"http://synthetichealth.github.io/synthea/disability-adjusted-life-years\",\"valueDecimal\":0.0},{\"url\":\"http://synthetichealth.github.io/synthea/quality-adjusted-life-years\",\"valueDecimal\":2.0}],\"identifier\":[{\"system\":\"https://github.com/synthetichealth/synthea\",\"value\":\"9547e8f0-42d5-48b2-96d2-dcc7e2d2c70e\"},{\"type\":{\"coding\":[{\"system\":\"http://terminology.hl7.org/CodeSystem/v2-0203\",\"code\":\"MR\",\"display\":\"Medical Record Number\"}],\"text\":\"Medical Record Number\"},\"system\":\"http://hospital.smarthealthit.org\",\"value\":\"9547e8f0-42d5-48b2-96d2-dcc7e2d2c70e\"},{\"type\":{\"coding\":[{\"system\":\"http://terminology.hl7.org/CodeSystem/v2-0203\",\"code\":\"SS\",\"display\":\"Social Security Number\"}],\"text\":\"Social Security Number\"},\"system\":\"http://hl7.org/fhir/sid/us-ssn\",\"value\":\"999-11-1542\"}],\"name\":[{\"use\":\"official\",\"family\":\"Dueñas839\",\"given\":[\"Leonor133\"]}],\"telecom\":[{\"system\":\"phone\",\"value\":\"555-890-8795\",\"use\":\"home\"}],\"gender\":\"female\",\"birthDate\":\"2016-12-16\",\"address\":[{\"extension\":[{\"url\":\"http://hl7.org/fhir/StructureDefinition/geolocation\",\"extension\":[{\"url\":\"latitude\",\"valueDecimal\":42.342933521629355},{\"url\":\"longitude\",\"valueDecimal\":-70.93353385375897}]}],\"line\":[\"126 Raynor Vale\"],\"city\":\"Boston\",\"state\":\"Massachusetts\",\"postalCode\":\"02108\",\"country\":\"US\"}],\"maritalStatus\":{\"coding\":[{\"system\":\"http://terminology.hl7.org/CodeSystem/v3-MaritalStatus\",\"code\":\"S\",\"display\":\"Never Married\"}],\"text\":\"Never Married\"},\"multipleBirthBoolean\":false,\"communication\":[{\"language\":{\"coding\":[{\"system\":\"urn:ietf:bcp:47\",\"code\":\"es\",\"display\":\"Spanish\"}],\"text\":\"Spanish\"}}]}")
        `shouldBe` Just Patient {
             patientId = Just "0001fd81-1d53-46f4-b673-0301496ba959"
           , patientMeta = Nothing
           , patientImplicitRules = Nothing
           , patientLanguage = Nothing
           , patientText = Just (Narrative {narrativeAttribs = [], narrativeId = Nothing, narrativeExtension = [], narrativeStatus = NsGenerated, narrativeXhtmlDiv = XhtmlDiv (Div [] [FText "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by <a href=\"https://github.com/synthetichealth/synthea\">Synthea</a>.Version identifier: v2.4.0-272-gbd747730\n .   Person seed: 292861142008678757  Population seed: 1563971124564</div>"])})
           , patientExtension = [
                          Extension {
                              extensionUrl = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race"
                            , extensionId = Nothing
                            , extensionExtension = [
                                Extension {
                                    extensionUrl = "ombCategory"
                                  , extensionId = Nothing
                                  , extensionExtension = []
                                  , extensionValue = Just (ExtensionValueCoding (Coding {codingAttribs = [], codingId = Nothing, codingExtension = [], codingSystem = Just "urn:oid:2.16.840.1.113883.6.238", codingVersion = Nothing, codingCode = Just "2054-5", codingDisplay = Just "Black or African American", codingUserSelected = Nothing}))}
                              , Extension {
                                    extensionUrl = "text"
                                  , extensionId = Nothing
                                  , extensionExtension = []
                                  , extensionValue = Just (ExtensionValueString "Black or African American")}
                              ]
                            , extensionValue = Nothing}
                        , Extension {
                              extensionUrl = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity"
                            , extensionId = Nothing
                            , extensionExtension = [
                                        Extension {
                                            extensionUrl = "ombCategory"
                                          , extensionId = Nothing
                                          , extensionExtension = []
                                          , extensionValue = Just (ExtensionValueCoding (Coding {codingAttribs = [], codingId = Nothing, codingExtension = [], codingSystem = Just "urn:oid:2.16.840.1.113883.6.238", codingVersion = Nothing, codingCode = Just "2186-5", codingDisplay = Just "Not Hispanic or Latino", codingUserSelected = Nothing}))}
                                      , Extension {
                                            extensionUrl = "text"
                                          , extensionId = Nothing
                                          , extensionExtension = []
                                          , extensionValue = Just (ExtensionValueString "Not Hispanic or Latino")}
                                      ]
                            , extensionValue = Nothing}
                        , Extension {
                              extensionUrl = "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName"
                            , extensionId = Nothing
                            , extensionExtension = []
                            , extensionValue = Just (ExtensionValueString "Ariadna374 Zapata667")}
                        , Extension {
                              extensionUrl = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex"
                            , extensionId = Nothing
                            , extensionExtension = []
                            , extensionValue = Just (ExtensionValueCode "F")}
                        , Extension {
                              extensionUrl = "http://hl7.org/fhir/StructureDefinition/patient-birthPlace"
                            , extensionId = Nothing
                            , extensionExtension = []
                            , extensionValue = Just (ExtensionValueAddress (Address {
                                              addressId = Nothing, addressExtension = [], addressUse = Nothing
                                            , addressType = Nothing
                                            , addressText = Nothing, addressLine = [], addressCity = Just "Wesley"
                                            , addressDistrict = Nothing, addressState = Just "Saint Andrew Parish"
                                            , addressPostalCode = Nothing, addressCountry = Just "DM", addressPeriod = Nothing}))}
                        , Extension {
                              extensionUrl = "http://synthetichealth.github.io/synthea/disability-adjusted-life-years"
                            , extensionId = Nothing
                            , extensionExtension = []
                            , extensionValue = Just (ExtensionValueDecimal 0.0)}
                        , Extension {
                              extensionUrl = "http://synthetichealth.github.io/synthea/quality-adjusted-life-years"
                            , extensionId = Nothing
                            , extensionExtension = []
                            , extensionValue = Just (ExtensionValueDecimal 2.0)}
                        ]
        , patientModifierExtension = []
        , patientIdentifier = [
                  Identifier {identifierAttribs = [], identifierId = Nothing, identifierExtension = [], identifierUse = Nothing, identifierType = Nothing, identifierSystem = Just "https://github.com/synthetichealth/synthea", identifierValue = Just "9547e8f0-42d5-48b2-96d2-dcc7e2d2c70e", identifierPeriod = Nothing, identifierAssigner = Nothing}
                , Identifier {identifierAttribs = [], identifierId = Nothing, identifierExtension = [], identifierUse = Nothing, identifierType = Just (CodeableConcept {codeableConceptAttribs = [], codeableConceptId = Nothing, codeableConceptExtension = [], codeableConceptCoding = [Coding {codingAttribs = [], codingId = Nothing, codingExtension = [], codingSystem = Just "http://terminology.hl7.org/CodeSystem/v2-0203", codingVersion = Nothing, codingCode = Just "MR", codingDisplay = Just "Medical Record Number", codingUserSelected = Nothing}], codeableConceptText = Just "Medical Record Number"}), identifierSystem = Just "http://hospital.smarthealthit.org", identifierValue = Just "9547e8f0-42d5-48b2-96d2-dcc7e2d2c70e", identifierPeriod = Nothing, identifierAssigner = Nothing}
                , Identifier {identifierAttribs = [], identifierId = Nothing, identifierExtension = [], identifierUse = Nothing, identifierType = Just (CodeableConcept {codeableConceptAttribs = [], codeableConceptId = Nothing, codeableConceptExtension = [], codeableConceptCoding = [Coding {codingAttribs = [], codingId = Nothing, codingExtension = [], codingSystem = Just "http://terminology.hl7.org/CodeSystem/v2-0203", codingVersion = Nothing, codingCode = Just "SS", codingDisplay = Just "Social Security Number", codingUserSelected = Nothing}], codeableConceptText = Just "Social Security Number"}), identifierSystem = Just "http://hl7.org/fhir/sid/us-ssn", identifierValue = Just "999-11-1542", identifierPeriod = Nothing, identifierAssigner = Nothing}]
        , patientActive = Nothing
        , patientName = [HumanName {humanNameAttribs = [], humanNameId = Nothing, humanNameExtension = [], humanNameUse = Just NuOfficial, humanNameText = Nothing, humanNameFamily = Just "Due\241as839", humanNameGiven = ["Leonor133"], humanNamePrefix = [], humanNameSuffix = [], humanNamePeriod = Nothing}]
        , patientTelecom = [ContactPoint {contactPointAttribs = [], contactPointId = Nothing, contactPointExtension = [], contactPointSystem = Just CpsPhone, contactPointValue = Just "555-890-8795", contactPointUse = Just CpuHome, contactPointRank = Nothing, contactPointPeriod = Nothing}]
        , patientGender = Just AgFemale
        , patientBirthDate = Just "2016-12-16"
        , patientDeceased = Nothing
        , patientAddress = [Address {addressId = Nothing, addressExtension = [Extension {extensionUrl = "http://hl7.org/fhir/StructureDefinition/geolocation", extensionId = Nothing, extensionExtension = [Extension {extensionUrl = "latitude", extensionId = Nothing, extensionExtension = [], extensionValue = Just (ExtensionValueDecimal 42.342933521629355)},Extension {extensionUrl = "longitude", extensionId = Nothing, extensionExtension = [], extensionValue = Just (ExtensionValueDecimal (-70.93353385375897))}], extensionValue = Nothing}], addressUse = Nothing, addressType = Nothing, addressText = Nothing, addressLine = ["126 Raynor Vale"], addressCity = Just "Boston", addressDistrict = Nothing, addressState = Just "Massachusetts", addressPostalCode = Just "02108", addressCountry = Just "US", addressPeriod = Nothing}]
        , patientMaritalStatus = Just (CodeableConcept {codeableConceptAttribs = [], codeableConceptId = Nothing, codeableConceptExtension = [], codeableConceptCoding = [Coding {codingAttribs = [], codingId = Nothing, codingExtension = [], codingSystem = Just "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus", codingVersion = Nothing, codingCode = Just "S", codingDisplay = Just "Never Married", codingUserSelected = Nothing}], codeableConceptText = Just "Never Married"})
        , patientMultipleBirth = Just (PatientMultipleBirthBoolean False)
        , patientPhoto = []
        , patientContact = []
        , patientCommunication = [PatientCommunication {
              patientCommunicationAttrId = Nothing
            , patientCommunicationExtension = []
            , patientCommunicationModifierExtension = []
            , patientCommunicationLanguage = CodeableConcept {codeableConceptAttribs = [], codeableConceptId = Nothing, codeableConceptExtension = [], codeableConceptCoding = [Coding {codingAttribs = [], codingId = Nothing, codingExtension = [], codingSystem = Just "urn:ietf:bcp:47", codingVersion = Nothing, codingCode = Just "es", codingDisplay = Just "Spanish", codingUserSelected = Nothing}], codeableConceptText = Just "Spanish"}, patientCommunicationPreferred = Nothing}]
        , patientGeneralPractitioner = []
        , patientManagingOrganization = Nothing
        , patientLink = []
        }
--
-- XML
--
    it "decode text" $ do
      decode "<Patient xmlns=\"http://hl7.org/fhir\"><text><status value=\"generated\"/><div xmlns=\"xhtml\">this is text</div></text></Patient>"
        `shouldBe` Right (PatientR Patient {
          patientId = Nothing
        , patientMeta = Nothing
        , patientImplicitRules = Nothing
        , patientLanguage = Nothing
        , patientText = Just (Narrative {narrativeAttribs = [], narrativeId = Nothing, narrativeExtension = [], narrativeStatus = NsGenerated, narrativeXhtmlDiv = XhtmlDiv (Div [] [FText "this is text"])})
        , patientExtension = []
        , patientModifierExtension = []
        , patientIdentifier = []
        , patientActive= Nothing
        , patientName = []
        , patientTelecom = []
        , patientGender = Nothing
        , patientBirthDate = Nothing
        , patientMultipleBirth = Nothing
        , patientAddress = []
        , patientMaritalStatus = Nothing
        , patientDeceased = Nothing
        , patientPhoto = []
        , patientContact = []
        , patientCommunication = []
        , patientGeneralPractitioner = []
        , patientManagingOrganization = Nothing
        , patientLink = []
        })
    it "decode" $ do
      decode "<Patient xmlns=\"http://hl7.org/fhir\" xml:id=\"123456\"><id value=\"123456\"></id><meta><versionId value=\"0\"></versionId><lastUpdated value=\"2021-06-10T12:59:59\"></lastUpdated></meta><identifier><use value=\"usual\"></use><type><coding><system value=\"orbis-pid\"></system><code value=\"ORBISPID\"></code></coding><text value=\"pid\"></text></type><system value=\"http://uk-koeln.de/ORBISPID\"></system><value value=\"6000001\"></value></identifier><identifier><use value=\"usual\"></use><type><coding><system value=\"orbis-pid\"></system><code value=\"ORBISPID\"></code></coding><text value=\"pid\"></text></type><system value=\"http://uk-koeln.de/ORBISPID\"></system><value value=\"6000001\"></value></identifier><active value=\"true\"></active><name><use value=\"official\"></use><text value=\"Dummy, Detlef, *2000-01-01\"></text><family value=\"Dummy\"></family><given value=\"Detlef\"></given><given value=\"Ralph\"></given><prefix value=\"Dr.med.\"></prefix><suffix value=\"Jr.\"></suffix><period><start value=\"2021-04-01T09:00:00\"></start></period></name><telecom><system value=\"phone\"></system><value value=\"0221-478-42160\"></value><use value=\"work\"></use><rank value=\"1\"></rank></telecom><gender value=\"female\"></gender><birthDate value=\"2021-01-01\"></birthDate><deceasedBoolean value=\"false\"></deceasedBoolean><address><use value=\"home\"></use><type value=\"postal\"></type><line value=\"Kerpenerstr. 62\"></line><city value=\"Köln\"></city><state value=\"NRW\"></state><postalCode value=\"50729\"></postalCode><country value=\"DEU\"></country></address><contact><name><use value=\"official\"></use><text value=\"Dummy, Detlef, *2000-01-01\"></text><family value=\"Dummy\"></family><given value=\"Detlef\"></given><given value=\"Ralph\"></given><prefix value=\"Dr.med.\"></prefix><suffix value=\"Jr.\"></suffix><period><start value=\"2021-04-01T09:00:00\"></start></period></name><address><use value=\"home\"></use><type value=\"postal\"></type><line value=\"Kerpenerstr. 62\"></line><city value=\"Köln\"></city><state value=\"NRW\"></state><postalCode value=\"50729\"></postalCode><country value=\"DEU\"></country></address><gender value=\"male\"></gender><organization id=\"123\"><reference value=\"nabu/organizations/kikl\"></reference><display value=\"UKK Kinderklinik\"></display></organization></contact><communication><language><coding><system value=\"urn:ietf:bcp:47\"></system><version value=\"v7\"></version><code value=\"nl-NL\"></code><display value=\"Dutch\"></display></coding><text value=\"lang\"></text></language><preferred value=\"true\"></preferred></communication><generalPractitioner id=\"123\"><reference value=\"nabu/practitioners/p-12345\"></reference><display value=\"Bönte, Anselm\"></display></generalPractitioner><managingOrganization id=\"123\"><reference value=\"nabu/organizations/kikl\"></reference><display value=\"UKK Kinderklinik\"></display></managingOrganization></Patient>"
        `shouldBe` Right (PatientR Patient{
          patientId = Just "123456"
        , patientMeta = Just (Meta {metaAttribs = [], metaId = Nothing, metaExtension = [], metaVersionId = Just "0", metaLastUpdated = Just "2021-06-10T12:59:59", metaSource = Nothing, metaProfile = [], metaSecurity = [], metaTag = []})
        , patientImplicitRules = Nothing
        , patientLanguage = Nothing
        , patientText = Nothing
        , patientExtension = []
        , patientModifierExtension = []
        , patientIdentifier = [mkIdentifier,mkIdentifier]
        , patientActive= Just True
        , patientName = [mkHumanName]
        , patientTelecom = [mkContactPoint]
        , patientGender = Just AgFemale
        , patientBirthDate = Just "2021-01-01"
        , patientMultipleBirth = Nothing
        , patientAddress = [mkAddress]
        , patientMaritalStatus = Nothing
        , patientDeceased = Just (PatientDeceasedBoolean False)
        , patientPhoto = []
        , patientContact = [PatientContact {
              patientContactAttrId = Nothing
            , patientContactExtension = []
            , patientContactModifierExtension = []
            , patientContactRelationship = [], patientContactName = Just (HumanName {humanNameAttribs = [], humanNameId = Nothing, humanNameExtension = [], humanNameUse = Just NuOfficial, humanNameText = Just "Dummy, Detlef, *2000-01-01", humanNameFamily = Just "Dummy", humanNameGiven = ["Detlef","Ralph"], humanNamePrefix = ["Dr.med."], humanNameSuffix = ["Jr."], humanNamePeriod = Just (Period {periodAttribs = [], periodId = Nothing, periodExtension = [], periodStart = Just "2021-04-01T09:00:00", periodEnd = Nothing})}), patientContactTelecom = [], patientContactAddress = Just (Address {addressId = Nothing, addressExtension = [], addressUse = Just AuHome, addressType = Just AtPostal, addressText = Nothing, addressLine = ["Kerpenerstr. 62"], addressCity = Just "K\246ln", addressDistrict = Nothing, addressState = Just "NRW", addressPostalCode = Just "50729", addressCountry = Just "DEU", addressPeriod = Nothing}), patientContactGender = Just AgMale, patientContactOrganization = Just (Reference {referenceAttribs = HM.fromList [("id","123")], referenceExtension = [], referenceReference = Just "nabu/organizations/kikl", referenceType = Nothing, referenceIdentifier = Nothing, referenceDisplay = Just "UKK Kinderklinik"}), patientContactPeriod = Nothing}]
        , patientCommunication = [PatientCommunication {
              patientCommunicationAttrId = Nothing
            , patientCommunicationExtension = []
            , patientCommunicationModifierExtension = []
            , patientCommunicationLanguage = CodeableConcept {codeableConceptAttribs = [], codeableConceptId = Nothing, codeableConceptExtension = [], codeableConceptCoding = [Coding {codingAttribs = [], codingId = Nothing, codingExtension = [], codingSystem = Just "urn:ietf:bcp:47", codingVersion = Just "v7", codingCode = Just "nl-NL", codingDisplay = Just "Dutch", codingUserSelected = Nothing}], codeableConceptText = Just "lang"}, patientCommunicationPreferred = Just True}]
        , patientGeneralPractitioner = [Reference {referenceAttribs = HM.fromList [("id","123")], referenceExtension = [], referenceReference = Just "nabu/practitioners/p-12345", referenceType = Nothing, referenceIdentifier = Nothing, referenceDisplay = Just "B\246nte, Anselm"}]
        , patientManagingOrganization = Just (Reference {referenceAttribs = HM.fromList [("id","123")], referenceExtension = [], referenceReference = Just "nabu/organizations/kikl", referenceType = Nothing, referenceIdentifier = Nothing, referenceDisplay = Just "UKK Kinderklinik"}) 
        , patientLink = []
        })
    it "decode min patient" $ do
      decode "<Patient xmlns=\"http://hl7.org/fhir\"><active value=\"true\"/><gender value=\"female\"/><birthDate value=\"2021-01-01\"/><deceasedBoolean value=\"false\"/></Patient>"
        `shouldBe` Right (PatientR Patient {
          patientId = Nothing
        , patientMeta = Nothing
        , patientImplicitRules = Nothing
        , patientLanguage = Nothing
        , patientText = Nothing
        , patientExtension = []
        , patientModifierExtension = []
        , patientIdentifier = []
        , patientActive= Just True
        , patientName = []
        , patientTelecom = []
        , patientGender = Just AgFemale
        , patientBirthDate = Just "2021-01-01"
        , patientMultipleBirth = Nothing
        , patientAddress = []
        , patientMaritalStatus = Nothing
        , patientDeceased = Just (PatientDeceasedBoolean False)
        , patientPhoto = []
        , patientContact = []
        , patientCommunication = []
        , patientGeneralPractitioner = []
        , patientManagingOrganization = Nothing
        , patientLink = []
        })
    it "encode" $ do
      bsEncode (Xmlbf.toXml Patient {
          patientId = Just "123456"
        , patientMeta = Just $ Meta {
              metaAttribs=[]
            , metaId= Nothing
            , metaExtension= []
            , metaVersionId=Just "0"
            , metaLastUpdated = Just "2021-06-10T12:59:59"
            , metaSource = Nothing
            , metaProfile = []
            , metaSecurity = []
            , metaTag = []
          }
        , patientImplicitRules = Nothing
        , patientLanguage = Nothing
        , patientText = Just mkNarrative
        , patientExtension = []
        , patientModifierExtension = []
        , patientIdentifier = [mkIdentifier,mkIdentifier]
        , patientActive= Just True
        , patientName = [mkHumanName]
        , patientTelecom = [mkContactPoint]
        , patientGender = Just AgFemale
        , patientBirthDate = Just "2021-01-01"
        , patientMultipleBirth = Nothing
        , patientAddress = [mkAddress]
        , patientMaritalStatus = Nothing
        , patientDeceased = Just (PatientDeceasedBoolean False)
        , patientPhoto = []
        , patientContact = [mkPatientContact]
        , patientCommunication = [mkPatientComm]
        , patientGeneralPractitioner = [mkReference "gp"]
        , patientManagingOrganization = Just $ mkReference "org"
        , patientLink = []
        }) `shouldBe` 
        "<Patient xmlns=\"http://hl7.org/fhir\"><id value=\"123456\"></id><meta><versionId value=\"0\"></versionId><lastUpdated value=\"2021-06-10T12:59:59\"></lastUpdated></meta><text><status value=\"generated\"></status><div xmlns=\"http://www.w3.org/1999/xhtml\">this is text</div></text><identifier><use value=\"usual\"></use><type><coding><system value=\"orbis-pid\"></system><code value=\"ORBISPID\"></code></coding><text value=\"pid\"></text></type><system value=\"http://uk-koeln.de/ORBISPID\"></system><value value=\"6000001\"></value></identifier><identifier><use value=\"usual\"></use><type><coding><system value=\"orbis-pid\"></system><code value=\"ORBISPID\"></code></coding><text value=\"pid\"></text></type><system value=\"http://uk-koeln.de/ORBISPID\"></system><value value=\"6000001\"></value></identifier><active value=\"true\"></active><name><use value=\"official\"></use><text value=\"Dummy, Detlef, *2000-01-01\"></text><family value=\"Dummy\"></family><given value=\"Detlef\"></given><given value=\"Ralph\"></given><prefix value=\"Dr.med.\"></prefix><suffix value=\"Jr.\"></suffix><period><start value=\"2021-04-01T09:00:00\"></start></period></name><telecom><system value=\"phone\"></system><value value=\"0221-478-42160\"></value><use value=\"work\"></use><rank value=\"1\"></rank></telecom><gender value=\"female\"></gender><birthDate value=\"2021-01-01\"></birthDate><deceasedBoolean value=\"false\"></deceasedBoolean><address><use value=\"home\"></use><type value=\"postal\"></type><line value=\"Kerpenerstr. 62\"></line><city value=\"K\195\182ln\"></city><state value=\"NRW\"></state><postalCode value=\"50729\"></postalCode><country value=\"DEU\"></country></address><contact><name><use value=\"official\"></use><text value=\"Dummy, Detlef, *2000-01-01\"></text><family value=\"Dummy\"></family><given value=\"Detlef\"></given><given value=\"Ralph\"></given><prefix value=\"Dr.med.\"></prefix><suffix value=\"Jr.\"></suffix><period><start value=\"2021-04-01T09:00:00\"></start></period></name><address><use value=\"home\"></use><type value=\"postal\"></type><line value=\"Kerpenerstr. 62\"></line><city value=\"K\195\182ln\"></city><state value=\"NRW\"></state><postalCode value=\"50729\"></postalCode><country value=\"DEU\"></country></address><gender value=\"male\"></gender><organization><reference value=\"nabu/organizations/kikl\"></reference><display value=\"UKK Kinderklinik\"></display></organization></contact><communication><language><coding><system value=\"urn:ietf:bcp:47\"></system><version value=\"v7\"></version><code value=\"nl-NL\"></code><display value=\"Dutch\"></display></coding><text value=\"lang\"></text></language><preferred value=\"true\"></preferred></communication><generalPractitioner><reference value=\"nabu/practitioners/p-12345\"></reference><display value=\"B\195\182nte, Anselm\"></display></generalPractitioner><managingOrganization><reference value=\"nabu/organizations/kikl\"></reference><display value=\"UKK Kinderklinik\"></display></managingOrganization></Patient>"

