-ifndef(QUERY_RESOURCES).
-define(QUERY_RESOURCES, true).
%%%
%%% FHIR 4.0.0 Search Parameter
%%%
-define(ALLOWED_KEYS, #{
  <<"active">> =>  [
        <<"token">>, <<"token">>,
        [],
        <<"Patient.active">>,
        true, true,
        undefined,
        [<<"missing">>,<<"text">>,<<"not">>,<<"in">>,<<"not-in">>,<<"below">>,
         <<"above">>,<<"ofType">>]},
    ],
  <<"address">> =>  [
        <<"string">>, <<"string">>,
        [],
        <<"Patient.address | Person.address | Practitioner.address | RelatedPerson.address">>,
        true, true,
        undefined,
        [<<"missing">>,<<"exact">>,<<"contains">>]},
    ],
  <<"address-city">> =>  [
        <<"string">>, <<"string">>,
        [],
        <<"Patient.address.city | Person.address.city | Practitioner.address.city | RelatedPerson.address.city">>,
        true, true,
        undefined,
        [<<"missing">>,<<"exact">>,<<"contains">>]},
    ],
  <<"address-country">> =>  [
        <<"string">>, <<"string">>,
        [],
        <<"Patient.address.country | Person.address.country | Practitioner.address.country | RelatedPerson.address.country">>,
        true, true,
        undefined,
        [<<"missing">>,<<"exact">>,<<"contains">>]},
    ],
  <<"address-postalcode">> =>  [
        <<"string">>, <<"string">>,
        [],
        <<"Patient.address.postalCode | Person.address.postalCode | Practitioner.address.postalCode | RelatedPerson.address.postalCode">>,
        true, true,
        undefined,
        [<<"missing">>,<<"exact">>,<<"contains">>]},
    ],
  <<"address-state">> =>  [
        <<"string">>, <<"string">>,
        [],
        <<"Patient.address.state | Person.address.state | Practitioner.address.state | RelatedPerson.address.state">>,
        true, true,
        undefined,
        [<<"missing">>,<<"exact">>,<<"contains">>]},
    ],
  <<"address-use">> =>  [
        <<"token">>, <<"token">>,
        [],
        <<"Patient.address.use | Person.address.use | Practitioner.address.use | RelatedPerson.address.use">>,
        true, true,
        undefined,
        [<<"missing">>,<<"text">>,<<"not">>,<<"in">>,<<"not-in">>,<<"below">>,
         <<"above">>,<<"ofType">>]},
    ],
  <<"birthdate">> =>  [
        <<"date">>, <<"date">>,
        [],
        <<"Patient.birthDate | Person.birthDate | RelatedPerson.birthDate">>,
        true, true,
        [<<"eq">>,<<"ne">>,<<"gt">>,<<"lt">>,<<"le">>,<<"sa">>,<<"eb">>,
         <<"ap">>],
        [<<"missing">>]},
    ],
  <<"death-date">> =>  [
        <<"date">>, <<"date">>,
        [],
        <<"(Patient.deceased as dateTime)">>,
        true, true,
        [<<"eq">>,<<"ne">>,<<"gt">>,<<"lt">>,<<"le">>,<<"sa">>,<<"eb">>,
         <<"ap">>],
        [<<"missing">>]},
    ],
  <<"deceased">> =>  [
        <<"token">>, <<"token">>,
        [],
        <<"Patient.deceased.exists() and Patient.deceased != false">>,
        true, true,
        undefined,
        [<<"missing">>,<<"text">>,<<"not">>,<<"in">>,<<"not-in">>,<<"below">>,
         <<"above">>,<<"ofType">>]},
    ],
  <<"email">> =>  [
        <<"token">>, <<"token">>,
        [],
        <<"Patient.telecom.where(system='email') | Person.telecom.where(system='email') | Practitioner.telecom.where(system='email') | PractitionerRole.telecom.where(system='email') | RelatedPerson.telecom.where(system='email')">>,
        true, true,
        undefined,
        [<<"missing">>,<<"text">>,<<"not">>,<<"in">>,<<"not-in">>,<<"below">>,
         <<"above">>,<<"ofType">>]},
    ],
  <<"family">> =>  [
        <<"string">>, <<"string">>,
        [],
        <<"Patient.name.family | Practitioner.name.family">>,
        true, true,
        undefined,
        [<<"missing">>,<<"exact">>,<<"contains">>]},
    ],
  <<"gender">> =>  [
        <<"token">>, <<"token">>,
        [],
        <<"Patient.gender | Person.gender | Practitioner.gender | RelatedPerson.gender">>,
        true, true,
        undefined,
        [<<"missing">>,<<"text">>,<<"not">>,<<"in">>,<<"not-in">>,<<"below">>,
         <<"above">>,<<"ofType">>]},
    ],
  <<"general-practitioner">> =>  [
        <<"reference">>, <<"reference">>,
        [<<"Practitioner">>,<<"Organization">>,<<"PractitionerRole">>],
        <<"Patient.generalPractitioner">>,
        true, true,
        undefined,
        [<<"missing">>,<<"type">>,<<"identifier">>]},
    ],
  <<"given">> =>  [
        <<"string">>, <<"string">>,
        [],
        <<"Patient.name.given | Practitioner.name.given">>,
        true, true,
        undefined,
        [<<"missing">>,<<"exact">>,<<"contains">>]},
    ],
  <<"identifier">> =>  [
        <<"token">>, <<"token">>,
        [],
        <<"Patient.identifier">>,
        true, true,
        undefined,
        [<<"missing">>,<<"text">>,<<"not">>,<<"in">>,<<"not-in">>,<<"below">>,
         <<"above">>,<<"ofType">>]},
    ],
  <<"language">> =>  [
        <<"token">>, <<"token">>,
        [],
        <<"Patient.communication.language">>,
        true, true,
        undefined,
        [<<"missing">>,<<"text">>,<<"not">>,<<"in">>,<<"not-in">>,<<"below">>,
         <<"above">>,<<"ofType">>]},
    ],
  <<"link">> =>  [
        <<"reference">>, <<"reference">>,
        [<<"Patient">>,<<"RelatedPerson">>],
        <<"Patient.link.other">>,
        true, true,
        undefined,
        [<<"missing">>,<<"type">>,<<"identifier">>]},
    ],
  <<"name">> =>  [
        <<"string">>, <<"string">>,
        [],
        <<"Patient.name">>,
        true, true,
        undefined,
        [<<"missing">>,<<"exact">>,<<"contains">>]},
    ],
  <<"organization">> =>  [
        <<"reference">>, <<"reference">>,
        [<<"Organization">>],
        <<"Patient.managingOrganization">>,
        true, true,
        undefined,
        [<<"missing">>,<<"type">>,<<"identifier">>]},
    ],
  <<"phone">> =>  [
        <<"token">>, <<"token">>,
        [],
        <<"Patient.telecom.where(system='phone') | Person.telecom.where(system='phone') | Practitioner.telecom.where(system='phone') | PractitionerRole.telecom.where(system='phone') | RelatedPerson.telecom.where(system='phone')">>,
        true, true,
        undefined,
        [<<"missing">>,<<"text">>,<<"not">>,<<"in">>,<<"not-in">>,<<"below">>,
         <<"above">>,<<"ofType">>]},
    ],
  <<"phonetic">> =>  [
        <<"string">>, <<"string">>,
        [],
        <<"Patient.name | Person.name | Practitioner.name | RelatedPerson.name">>,
        true, true,
        undefined,
        [<<"missing">>,<<"exact">>,<<"contains">>]},
    ],
  <<"telecom">> =>  [
        <<"token">>, <<"token">>,
        [],
        <<"Patient.telecom | Person.telecom | Practitioner.telecom | PractitionerRole.telecom | RelatedPerson.telecom">>,
        true, true,
        undefined,
        [<<"missing">>,<<"text">>,<<"not">>,<<"in">>,<<"not-in">>,<<"below">>,
         <<"above">>,<<"ofType">>]},
    ],
    }).
%%%
-define(TYPE_KEYS, #{
  <<"Patient">> =>  [
    <<"active">>,
    <<"address">>,
    <<"address-city">>,
    <<"address-country">>,
    <<"address-postalcode">>,
    <<"address-state">>,
    <<"address-use">>,
    <<"birthdate">>,
    <<"death-date">>,
    <<"deceased">>,
    <<"email">>,
    <<"family">>,
    <<"gender">>,
    <<"general-practitioner">>,
    <<"given">>,
    <<"identifier">>,
    <<"language">>,
    <<"link">>,
    <<"name">>,
    <<"organization">>,
    <<"phone">>,
    <<"phonetic">>,
    <<"telecom">>
    ]
    }).
